title: The Minnesota State High School Fencing League
description: Information regarding the MNHSFL.

# Minima theme v2.5.0
theme: minima
sass:
  style: compressed
  load_paths:
    - assets

# Exclude internal files from site
exclude:
  - README.md

# Minima config (see https://github.com/jekyll/minima/blob/v2.5.0/README.md)
minima:
  skin: solarized
  social_links:
    - { platform: facebook, user_url: "https://www.facebook.com/mnhsfl" }
    - { platform: email, user_url: "info@mnhsfl.org" }

# Only show these pages in the top navigation
header_pages:
  - policies/index.md